update some scripts to be more current

diff --git a/script/do_i_have_everything_installed_right b/script/do_i_have_everything_installed_right
--- a/script/do_i_have_everything_installed_right
+++ b/script/do_i_have_everything_installed_right
@@ -4,6 +4,8 @@ STATUS=0
 p=$0
 DEBUG=false
 AUTO_INSTALL=false
+AUTO_INSTALL_PACKAGES=
+RAILS_VERSION=2.3.14
 
 helpme(){
 echo "Usage: $(basename $0) [options]"
@@ -38,16 +40,31 @@ while [ -n "$1" ]; do
 done
 
 fail(){
-    STATUS=1
-    echo "FAILED"
-    echo "  $@"
+    if [ "$AUTO_INSTALL" = "true" ]; then
+	echo "FAILED"
+	echo "  will auto-install $@"
+	AUTO_INSTALL_PACKAGES="$AUTO_INSTALL_PACKAGES $@"
+    else
+	STATUS=1
+	echo "FAILED"
+	echo "  install $@"
+    fi
+}
+
+install_pkg() {
+    sudo apt-get install -y "$@"
 }
 
 error(){
     fail "$@"
-    echo
-    echo "After doing that, retry this script."
-    exit $STATUS # 1
+    if [ "$AUTO_INSTALL" = "true" ] ; then
+	echo "  installing early to allow further testing:"
+	install_pkg "$@"
+    else
+	echo
+	echo "After doing that, retry this script."
+	exit $STATUS # 1
+    fi
 }
 
 start(){
@@ -113,12 +130,23 @@ check_a_version(){
     ruby -r "$(dirname $p)/../config/boot.rb" -e "test_version($(echo $@ | sed 's/[.]/,/g'))"
 }
 
+auto_install() {
+    if [ "$AUTO_INSTALL" = "true" ] ; then
+	if [ -n "$AUTO_INSTALL_PACKAGES" ]; then
+	    echo "Now auto-installing packages: $@"
+	    install_pkg "$AUTO_INSTALL_PACKAGES"
+	else
+	    echo "Nothing needs to be installed."
+	fi
+    fi
+}
+
 check_for_postgres(){
     [ -n "$(pgrep -x postgres)$(pgrep -x postmaster)" ]
 }
 
 test_my_rails_version(){
-    check_a_version 2.3.14
+    check_a_version $RAILS_VERSION
 }
 
 test_find_thin(){
@@ -127,27 +155,28 @@ test_find_thin(){
 
 echo "Testing to see if you have everything required for fgdb to run..."
 echo
-run "Checking to see if ruby is installed..." "which ruby" "install ruby" "error"
+run "Checking to see if ruby is installed..." "which ruby" "ruby" "error"
 setup_stuff # only runable if ruby is installed
-run "Checking to see if make is installed..." "which make" "install make" "fail"
-run "Checking to see if rails is installed..." "ruby $(dirname $0)/../config/boot.rb" "install rails" "error"
-run "Checking to see if rails is correct version..." "test_my_rails_version" "use rails version 2.3.5" "fail"
-run "Checking to see if the ruby postgres bindings are installed..." "require_test pg" "install libpgsql-ruby" "fail"
-run "Checking to see if nokogiri is installed..." "require_test nokogiri" "install libnokogiri-ruby" "fail"
-run "Checking to see if barby is installed..." "require_test barby" "install libbarby-ruby" "fail"
-run "Checking to see if bluecloth is installed..." "require_test bluecloth" "install libbluecloth-ruby" "fail"
-run "Checking to see if rmagick is installed..." "require_test RMagick" "install librmagick-ruby" "fail"
-run "Checking to see if bytes is installed..." "require_test bytes" "install libbytes-ruby1.8" "fail"
-run "Checking to see if prawn is installed..." "require_test prawn" "install ruby-prawn" "fail"
-run "Checking to see if json is installed..." "require_test json" "install libjson-ruby1.8" "fail"
-run "Checking to see if RT::Client::REST is installed..." "require_perl_test RT::Client::REST" "install librt-client-rest-perl" "fail"
-run "Checking to see if xmlstarlet is installed..." "which xmlstarlet" "install xmlstarlet" "fail"
-run "Checking to see if thin is installed..." "test_find_thin" "install thin" "fail"
-run "Checking to see if curl is installed..." "which curl" "install curl" "fail"
-run "Checking to see if socat is installed..." "which socat" "install socat" "fail"
-run "Checking to see if ruby gnuplot is installed..." "require_test gnuplot" "install libgnuplot-ruby" "fail"
-run "Checking to see if postgres is installed and running..." "check_for_postgres" "install and start postgres" "fail"
-run "Checking to see if timeout is installed..." "which timeout" "install timeout" "fail"
+run "Checking to see if make is installed..." "which make" "make" "fail"
+run "Checking to see if rails is installed..." "ruby $(dirname $0)/../config/boot.rb" "rails" "error"
+run "Checking to see if rails is correct version ($RAILS_VERSION)..." "test_my_rails_version" "rails" "fail"
+run "Checking to see if the ruby postgres bindings are installed..." "require_test pg" "ruby-pg" "fail"
+run "Checking to see if nokogiri is installed..." "require_test nokogiri" "ruby-nokogiri" "fail"
+run "Checking to see if barby is installed..." "require_test barby" "ruby-barby" "fail"
+run "Checking to see if bluecloth is installed..." "require_test bluecloth" "ruby-bluecloth" "fail"
+run "Checking to see if rmagick is installed..." "require_test RMagick" "ruby-imagemagick" "fail"
+run "Checking to see if bytes is installed..." "require_test bytes" "ruby-bytes" "fail"
+run "Checking to see if prawn is installed..." "require_test prawn" "ruby-prawn" "fail"
+run "Checking to see if RT::Client::REST is installed..." "require_perl_test RT::Client::REST" "librt-client-rest-perl" "fail"
+run "Checking to see if xmlstarlet is installed..." "which xmlstarlet" "xmlstarlet" "fail"
+run "Checking to see if thin is installed..." "test_find_thin" "thin" "fail"
+run "Checking to see if curl is installed..." "which curl" "curl" "fail"
+run "Checking to see if socat is installed..." "which socat" "socat" "fail"
+run "Checking to see if ruby gnuplot is installed..." "require_test gnuplot" "ruby-nokogiri" "fail"
+run "Checking to see if postgres is installed and running..." "check_for_postgres" "postgresql" "fail"
+run "Checking to see if timeout is installed..." "which timeout" "timeout" "fail"
+
+auto_install
 
 exit $STATUS
 
